### ISSUE TITLE
Property field Broken in Set Script Property Action 

### ISSUE THREAD

**Issue by nikosurfing** [evasiongames/gameflow#108]
Unity version 2018.3.14f1 (25 April 2019) with Gameflow version 1.2.0 and1.2.1. The Property field is broken in "set script property" action. 

To reproduce:

1. Create blank new project, and make sure the newest version of GameFlow is imported
2. Create sample script with public variable:
```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Script : MonoBehaviour
{
    public string testSTRING;
    public bool TestBool;

    public void testScript()
    {
        Debug.Log( "Test running script");
    }
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}

```
3.  Create new object and add gameflow component
4. Attach sample script to new object
5. Add the OnStart program to the GameFlow component.
6. Add "Set script property" action and drag script to component
7. You can't select any property to set the script

This is the sample project:
[download](https://www.dropbox.com/s/cst6txde2i8vtcd/SetScriptBug.unitypackage?dl=0)

**Comment by nikosurfing** [comment]
I really need this action to work to my current project (i was upgrade from unity 2017 to 2018, can't rolliback again this time). Can i use another actions to replace "set script property" or another trick to do that? 

edit: change typo of unity version

**Comment by evasiongames** [comment]
No workarounds for this, sorry. Please contact support@evasiongames.com (indicating your Asset Store purchase order number) and we will send you a new version with the fix as soon as possible.

**Comment by nikosurfing** [comment]
Hi, about my previous message, i forgot to attached my document invoice number. So, please take a look PDF on this email. Thank you

Best regards,
Eka bagus (nikosurfing)

Sent from Mailbird [http://www.getmailbird.com/?utm_source=Mailbird&amp;utm_medium=email&amp;utm_campaign=sent-from-mailbird]
On 03/05/2019 13:58:49, Evasion Games <notifications@github.com> wrote:
No workarounds for this, sorry. Please contact support@evasiongames.com [mailto:support@evasiongames.com] and we will send you a new version with the fix as soon as possible.

**Comment by nikosurfing** [comment]
Thank you, I was accidentally drop purchase order number on this github, but i sent it to your email support. please check your mail.

**Comment by mediedel** [comment]
Hi!
There is a workaround. If you alter your script and add a method with return value (the variable you want to pass to GF), you can use an invoke method in GF to get the variable from script.
