### ISSUE TITLE
"On Trigger Stay" does not update "Other -> Value:" if the colliding Object leaves the Trigger

### ISSUE THREAD

**Issue by Tvisvarson** [evasiongames/gameflow#122]
"On Trigger Stay" does not update Parameter "Other -> Value:" if the colliding Object leaves the Trigger. Instead it keeps the last collision.

unity 2019.1.2f1
GameFlow v1.2.5

**Comment by evasiongames** [comment]
This is not an issue but the way Unity works. When an object leaves the trigger the corresponding On Trigger Stay program will stop being executed, so keeping the last value for "Other" makes sense. If you need to do something at the exact moment the object leaves the trigger just use an On Trigger Exit program.
