### ISSUE TITLE
In tutorial02 needs to mention adding rigidbody

### ISSUE THREAD

**Issue by monsterbrain** [evasiongames/gameflow#14]
Hi,

   Just want to tell you that in tutorial 2 [https://evasiongames.github.io/gameflow/tutorials/tutorial02](https://evasiongames.github.io/gameflow/tutorials/tutorial02) I think, it needs to be mentioned to add a cube with rigidbody (of course, those who knew will add it, but might help new users I guess)

**Comment by evasiongames** [comment]
You are absolutely right. These tutorials need a revision, but we will do it after the v1.0 release. In the meantime I have just added a note in step 1.

Thanks.
