### ISSUE TITLE
Music loop stops if play sound SFX

### ISSUE THREAD

**Issue by nikosurfing** [evasiongames/gameflow#23]
If you play music with loop condition, and then you play another sound sfx. The music loop stops. It tested on android build, not in editor.

**Comment by nikosurfing** [comment]
These are 2 the example APK that using GF0.9 vs GF1.0. On previous GF0.9, music loops not stop even sound sfx was played, but on the GF1.0 music loops stop when any sfx played. Please download the apk below:
https://www.dropbox.com/s/lc5bcjz1sjpkz83/Test_music_loops.zip?dl=0

**Comment by nikosurfing** [comment]
Would it be fixed in the next update? Music loop is the important feature that it should works on mobile platform.

**Comment by evasiongames** [comment]
No, it won't be fixed for the next update (1.0.1). This issue has to be confirmed first, then it will be assigned to the Backlog and finally it will be scheduled for a future update. Please be patient, the issue will be fixed eventually.

**Comment by evasiongames** [comment]
By the way, providing the APKs is not very useful in this case. The ideal information we would need to confirm the issue is a minimal test project exposing the problem. The sooner the problem can be reproduced on our side, the sooner it could be fixed.

**Comment by jaylarkstudios** [comment]
I've just encountered this as well. It works in the Unity editor just fine, but after building and running in Android, the music doesn't loop. I've included my steps to reproduce the issue below:

1. Create a new Unity project and import GameFlow, a music track, and a sound effect.
2. Create an empty game object (named "Music" for convenience) and add the GameFlow component to that object.
3. Add the On Start block.
4. Inside On Start, add the Play Music action. Add your music track to the Audio Clip field and make sure Loop is checked.
5. Create another empty game object (this one named "Sound") and add the GameFlow component.
6. Add the On Start block, then inside On Start add a Loop action.
7. Inside the Loop, add a Play Sound action and add your sound effect to the Audio Clip field.
8. Add a Wait action right after the Play Sound action. Set the duration to a little bit longer than the sound effect.
9. Build the project as an Android build, and install the APK on your device. (I'm testing on a Nexus 5X.)
10. Open the app. You should hear the music play and the sound effect repeating. After finishing the music track once though, it does not repeat, though the sound effect continues to do so.

Here's a link where you can download the Unity project I used to reproduce the bug:
https://drive.google.com/file/d/1jY4o82jPuWthuqHvsFHD6ePdGOHogINs/view?usp=sharing

**Comment by jaylarkstudios** [comment]
One possible workaround is to put the Play Music action inside of a Loop, followed by a Wait that is approximately as long as the music track is. However, whenever the music starts playing, it interrupts any sound effect that is currently playing.

**Comment by nikosurfing** [comment]
@inejwstine: hi, is it not fixed yet on 1.1?

**Comment by jaylarkstudios** [comment]
Yes, I acquired GameFlow just a couple weeks ago. According to my
[Version].txt, I'm using v 1.1.1.

**Comment by nikosurfing** [comment]
@inejwstine : Hi, i can confirmed that this issue still there (v.1.1), i am surprised that i was report it about 3-4 months ago and still not fixes. This is serious issue. I am not sure which is stable version of GF right now

**Comment by evasiongames** [comment]
> Hi, i can confirmed that this issue still there (v.1.1), i am surprised that i was report it about 3-4 months ago and still not fixes. This is serious issue. I am not sure which is stable version of GF right now

Well, this issue was blocked because apparently you did not understand that we were asking you to provide more information in order to confirm the issue. Now that @inejwstine has provided the exact information we needed (thanks, Joshua) we will be able to fix the issue (if possible).

**Comment by evasiongames** [comment]
Issue confirmed. This is not related to Android.

**Comment by evasiongames** [comment]
Fixed.

**Comment by nikosurfing** [comment]
I am sorry, next time I will give more information and thank for your hard work.
