### ISSUE TITLE
Pooling Crash of Unity with Self Reference

### ISSUE THREAD

**Issue by dissidently** [evasiongames/gameflow#29]
Entirely my fault. Was trying to work out how Pooling and GameFlow work.

Added a Pool to an object, then added that same object to its own pool. Set the quantity to 20. Hit Play. Crashed Unity instantly.

I have since tried creating a pool on an empty game object and adding the desired sprite to the Pool, and making 20 copies. That works. It was just my stupidity, I had to try, to see if a pool cold be on the object to be pooled.

**Comment by nikosurfing** [comment]
What Unity version?
