### ISSUE TITLE
On Deactivate event not working

### ISSUE THREAD

**Issue by nikosurfing** [evasiongames/gameflow#30]
On GF 1.0.1 "On Deactivate" event not working, all actions inside that event not triggered even once.

**Comment by evasiongames** [comment]
On Deactivate programs work here. What do you have in the field 'In GameObject' of the On Deactivate? If it is a reference to the same GameObject containing the On Deactivate, then it is normal that the program is never executed, because no programs are executed in a deactivated GameObject.
