### ISSUE TITLE
Spurious 'KISS' warning

### ISSUE THREAD

**Issue by evasiongames** [evasiongames/gameflow#49]
This warning appears on rare situations apparently masking the actual error or warning. Reported example showing it:

![35949117_215368169077992_8385928765041016832_n](https://user-images.githubusercontent.com/7121057/44168275-02c6eb80-a0d1-11e8-83bc-afdb26bd1ca2.jpg)

**Comment by evasiongames** [comment]
The message is correct. I can count more than 3 levels of nesting in your screenshot.

**Comment by Tvisvarson** [comment]
it is, but it works... :) can't se the code because of the message, but the code below the if statement is there and works. so, i'm happy, but the message therefore is lying? I mean, you can leave it as it is, as long as it works for me.
