### ISSUE TITLE
Several  Object Can't Interpolate To One Color At Once

### ISSUE THREAD

**Issue by GeorgeDziov** [evasiongames/gameflow#5]
Instead they interpolate after each other, ordered.

**Comment by evasiongames** [comment]
Have you tried putting the Interpolate Color actions inside a Group action?

**Comment by GeorgeDziov** [comment]
Works like a charm! But that sequential interpolation is kinda cool too,
may be very useful for some complex stuff! Thanks for hint!

2015-11-03 20:52 GMT+03:00 Evasion Games <notifications@github.com>:
