### ISSUE TITLE
"Invoke Method" doesn't work on builds

### ISSUE THREAD

**Issue by nikosurfing** [evasiongames/gameflow#63]
On Gameflow 1.1, "invoke method" action with android build doesn't respond anything. I tested with new project and export it to APK and i can confirm it that "invoke metod" doesn't work on current version of gameflow

EDIT: I just tried to build to another platform like windows x86 /exe and it doesn't works. I think this issue occur on all platforms build.

**Comment by evasiongames** [comment]
You need to provide more information:

* What OS are you using? 
* What Unity version are you using? 
* What Android version in your device? 
* What are your Player settings? 
* Have you verified that the program where you use the Invoke Method action is actually executing in the device?
* What method are you invoking with the action?

**Comment by nikosurfing** [comment]
- OS using Windows 10 64bit home edition
- Using Unity 2017.4
- Tested on Android Oreo and Jellybean
- Player setting is default unity 
- I am verified that program doesn't executed on "invoke method" action
- I tried to change color / fade

nb: i also tried using Gameflow 1.0.1 to ensuring that this issue only occur on GF1.1 only. And yes, on previous version is works perfectly. Just happened to GF1.1

**Comment by evasiongames** [comment]
Thanks for the infos. These are important in order to find and fix the problem.

> I tried to change color / fade

Could you please be more specific? What method of what MonoBehaviour is that?

> nb: i also tried using Gameflow 1.0.1 to ensuring that this issue only occur on GF1.1 only. And yes, on previous version is works perfectly. Just happened to GF1.1

That's a good test, thanks. However it does not necessarily mean that the real problem is the Invoke Method action. It could be another problem related to execution of the program, so it is important that you verify that the program (what is it, an On Start?) containing the Invoke Action is really executing in v1.1.

**Comment by nikosurfing** [comment]
I am worried to use my real project as my project using "invoke method" a lot. 
So for testing purpose, , i create a new project, import GF from asset store, and create some UI object such as button and image.

- UI Button > Onclick > Invoke method (image) > CrossFadeColor ( change to any other color). 
- Export it to any platform (for this testing, i tried to publish android and windows exe platform), finish.
- On the published app, I clicked on button doesn't execute "CrossFadeColor" method

And then, still on the same test project, i replace Gameflow V1.1 to lower version 1.0.1. Publish again, but method action is now working. 

Hope you understand, please forgive my english, trying so hard to write in english

EDIT: I was testing to update my REAL project and export it to android, all of my object that using "invoke method" is not respon anything (not freeze or crash, just not executing method action)

**Comment by evasiongames** [comment]
Fixed. As I supposed the cause was not the action itself (the code has not been modified since v1.0) but an improper initialization of a dependency.
