### ISSUE TITLE
Interpolate not working on first "On Activate"

### ISSUE THREAD

**Issue by jaylarkstudios** [evasiongames/gameflow#68]
The "On Activate" program seems to get stuck on the Interpolate action when run for the first time. After the first time, it runs fine.

To reproduce:
1. Download this sample project that contains a large cube and two smaller ones. The object is to get the large cub to interpolate its position to the first smaller cube, and then back to the second when the appropriate GameFlow object is activated:
https://drive.google.com/file/d/1Iq9M98w5tOW0rYUX3ByYFLOJSHB6gMWb/view?usp=sharing
2. Open the scene "cubeBug.unity". Make sure that the gameobject "MoveCubeOnActivate_Bug" is deactivated.
3. Run the scene, then activate the gameobject "MoveCubeOnActivate_Bug". Note how the large cube does not move at all. When watching the GameFlow program, it appears to have gotten stuck on the Interpolate action.
4. Deactivate the gameobject, and then activate it again. This time it works, and the big cube moves to one small cube, and then back to the other.

I did find a possible workaround. Since it isn't working properly the first time the gameobject is activated, I started it as active, and added a program block that immediate deactivates it when the scene is run. That way the second time the gameobject is activated, it will work as expected. (See the gameobject called "MoveCubeOnActivate_Workaround" to see how I did it.)

**Comment by evasiongames** [comment]
Fixed. It was again a problem related to the initialization of the blocks.
