### ISSUE TITLE
Make waiting optional on interpolate actions

### ISSUE THREAD

**Issue by jaylarkstudios** [evasiongames/gameflow#69]
Feature request:

There are times when I want two things to interpolate at the same time. Currently, if I put one interpolate action right after the other, the program will wait for the first one to finish before moving on to the next one.

If I want them both to interpolate at the same time, one possible solution is to put them each in their own On Demand program, and then call them both with the Execute Program action, leaving the Wait option unchecked so they happen simultaneously. But it would be convenient if the Interpolate, Interpolate Color, and Interpolate Value actions also had a Wait option that could be turned on or off.

**Comment by jaylarkstudios** [comment]
@evasiongames Ah, right you are. That works just fine and is much simpler than what I was doing. Apologies; I'm still learning the different capabilities of GameFlow.

**Comment by evasiongames** [comment]
No problem :)
