### ISSUE TITLE
Invoke Method not working in On Click

### ISSUE THREAD

**Issue by jaylarkstudios** [evasiongames/gameflow#73]
The Invoke Method action is failing to run inside of the On Click program, even after deactivating and reactivating the game object (which sometimes successfully "reinitializes" the gameflow block). It works fine in the editor, but in an Android build, it fails.
To reproduce:
1. Download this sample project, which contains a single button and an empty game object called StartObject, both of which have a GameFlow component. There's also a game object called ButtonMethodsObject which has a simple script attached with two public methods (TestStart() and TestButton()) that just log messages to the console to show they were successfully called. Finally, due to the issue of blocks sometimes not initializing correctly (which I believe is a known issue) there is also a game object called Initializer. All it does is reactivate Button and StartObject when they are deactivated, which I do as soon as the program starts in order to reinitialize the blocks.
https://drive.google.com/file/d/12xzV0og0NP6OJ1FYvHv9XwhAfQL41kL2/view?usp=sharing
2. Run the main scene in the editor. When StartObject is first activated, its On Activate program should run Invoke Method on TestStart(). Then, when the button is clicked by the user, its On Click program should run Invoke Method on TestButton(). Verify that both are happening by checking for the corresponding success messages in the console.
3. Make an Android build, and install it on your device. Attach your device to a debugger so you can see the logs. (Alternatively, you can just use the APK I included in the Builds folder of the sample project you downloaded.)
4. Run the app on your Android device. Among the log messages from Unity, you should see the message that says "TestStart called successfully!"
5. Tap the button, and note that nothing happens, and the log message "TestButton called successfully!" does *not* appear.

In the logs, there are also several errors that appear to indicate that the InvokeMethod block on the button failed to initialize, even after being deactivated and activated again.

**Comment by jaylarkstudios** [comment]
Here's a copy of the logs when I ran the app on my own Android device:
[log.txt](https://github.com/evasiongames/gameflow/files/2537192/log.txt)

**Comment by jaylarkstudios** [comment]
After updating the test project to Unity 2018.2.15f1 and rebuilding, the problem persists.

**Comment by evasiongames** [comment]
According to the sample project, you are using GameFlow v1.1.1 which is not the latest GameFlow version. A similar issue was fixed in v1.1.2 (https://github.com/evasiongames/gameflow/issues/63), so please make sure to update the product through the Asset Store.

It is important that as soon as possible you remove the sample project from Google Drive as it contains a full copy of GameFlow and you made it publicly available. This is not allowed and breaks the Asset Store EULA.

**Comment by jaylarkstudios** [comment]
Sorry about that @evasiongames. I've disabled the link. What's the preferred method for sharing sample projects for bug reproduction purposes?

I'll also update GameFlow to the newest version as soon as I can and report back. (And I'll remember to check for updates in the future before making a bug report.)

**Comment by jaylarkstudios** [comment]
Updated to the newest version, and it's working now. The exceptions are no longer being thrown at the beginning, and the log messages are displaying as expected.

**Comment by evasiongames** [comment]
> Sorry about that @evasiongames. I've disabled the link. What's the preferred method for sharing sample projects for bug reproduction purposes?

Using Google Drive or Dropbox is fine as soon as the sample projects don't include the GameFlow folder.
