### ISSUE TITLE
Grouped actions cause NullReferenceException

### ISSUE THREAD

**Issue by jaylarkstudios** [evasiongames/gameflow#74]
Unity version 2018.2.151f1. After updating to GameFlow v1.1.2 the Group action is throwing a NullReferenceException, as long as it contains at least one action. I've tried several different actions inside the Group action, and they all cause an exception to be thrown, though the message displayed varies.

When the Group contains Interpoplate or Wait actions, the exception reads
```
NullReferenceException: Object reference not set to an instance of an object
GameFlow.TimeAction.StartTimer ()
GameFlow.TimeAction._OnSetup ()
GameFlow.Block.Setup ()
GameFlow.Group.OnSetup ()
GameFlow.Block._OnSetup ()
GameFlow.Block.Setup ()
GameFlow.Sequence.Step (Boolean ignoreBreakpoint)
GameFlow.Program.Step (Boolean ignorePause)
GameFlow.Program.Update ()
```

When the Group contains Set Variable Value or Play Sound actions, the exception reads
```
NullReferenceException: Object reference not set to an instance of an object
GameFlow.Group.OnExecute ()
GameFlow.Sequence.Step (Boolean ignoreBreakpoint)
GameFlow.Program.Step (Boolean ignorePause)
GameFlow.Program.Update ()
```

If the Group action is empty, it does not throw an exception.

**To reproduce:**

1. Create a new scene and make sure the newest version of GameFlow is imported.
2. Create three cubes. Position one in the middle and deactivate it. This will be the interpolate target. Move the other two to opposite ends of the screen.
2. Attach the GameFlow component to the Main Camera.
3. Add the OnStart program to the GameFlow component.
4. Add two Interpolate actions, and have both side cubes interpolate their position to the middle cube.
5. Run the scene. The two cubes should move to the center, one right after the other.
6. Stop the scene, and create a Group action in the GameFlow component, and then move both interpolate actions inside the group.
7. Run the scene again. This time, the cubes do not move, and the console is filled with NullReferenceException messages.

**Comment by evasiongames** [comment]
Fixed.
