### ISSUE TITLE
Object Spawned from Pool not shown as "Source" in "On Mouse Over"

### ISSUE THREAD

**Issue by Tvisvarson** [evasiongames/gameflow#90]
Instructions:
```
-open new scene
-create 3d object -> Sphere -> name it "MySphere"
   Set Transform -> Position -> X -> -2
-create 3d object -> Cube -> name it "MyCube"
-create GameFlow -> Pool -> name it "MyPool"
   drag object "MyCube" to "Model" of "Pool"
   set "Capacity" to 1
-create empty, call it "code"
   -add componet "Game Flow" to "code"
      -add "On Start" to "GameFlow(Script)"
         -add Action "Get Object From Pool"
            add "MyPool" to Pool
            ActivateObject -> check
         -add output variable by clicking on plus  
            rename new variable "MyCubeFromPool"
         -add action "Set Position"
            add "MyCubeFromPool" to Transform
            set Position x=2, y=0, z=0
            leave rest as set
     -add "On Mouse Over" to "GameFlow(Script)"
         change "In GameObject" to "In Scene"
         click the fat "=" sign to open up "Parameters" of "On Mouse Over"
         click "Source" to show what's the source beneath the mouse pointer
```

->Run the Game

If you hover over the left sphere, the value of the Source of "On Mouse Over" is "MySphere", if you hover over the center cube it is "MyCube". If you hover over the right cube (created from "MyPool") the Source does not change, like this cube is not there, but it should show "MyCube0" as you can see in the Variable "MyCubeFromPool".

I think there is a bug, isn't it?

**Comment by Tvisvarson** [comment]
Gameflow v.1.1.2 / Unity 2018.2.18f1

**Comment by evasiongames** [comment]
Thanks for the detailed reporting. I just build a scene following your instructions and it works as intended, so for now I can't reproduce nor confirm the issue.

I am using macOS, but that should not make any difference in this case. Anyway and just in case, can you please import the attached scene into your project and test it? 

[Issue90.unity.zip](https://github.com/evasiongames/gameflow/files/2809384/Issue90.unity.zip)

Thanks!

**Comment by evasiongames** [comment]
Ok, I found something: if the cube used as model is disabled initially, then the issue reproduces, but it has nothing to do with Pools. It is probably an issue caused by a bad or missing initialization.

**Comment by evasiongames** [comment]
Just make sure to have the "model" GameObject active initially to ensure a proper initialization of the internal controllers. You can then make a Deactivate GameObject in a On Start program if you want to hide the model.

**Comment by Tvisvarson** [comment]
I tried to understand and to do what you suggest, but i'm not intirely sure what it means. should i activate the source model for the one in the pool on start?
like:
on start-> activate game object?

**Comment by evasiongames** [comment]
No, what I am saying is the opposite. The issue does not reproduce if you have the model GameObject activated in the Editor when you enter in Play mode, so the workaround is just that: leave the model activated initially and use a Deactivate GameObject action in a On Start program if for any reason you need to have the model hidden. As On Start executes in the first frame, you should notice no difference.

**Comment by evasiongames** [comment]
Anyway this is just a workaround, I will try to have this fixed for the next update.

**Comment by evasiongames** [comment]
Fixed.
