### ISSUE TITLE
Animation Frames

### ISSUE THREAD

**Issue by Tvisvarson** [evasiongames/gameflow#91]
Is there a way to get the animation frame of the actual running animation? Or a way to fire a event at a certain frame? i'm not sure if this is the right place to ask... but i do not know where else.

**Comment by evasiongames** [comment]
The answer to both questions is that we don't have specific actions for that yet, sorry. These will be added in a future version. In the meantime you can try with some C# scripting:

* https://stackoverflow.com/questions/44821663/finding-the-specific-frame-an-animation-is-on-unity-2d
* https://answers.unity.com/questions/1013423/animation-state-get-current-frame.html
 
This issuetracker is for issues, feature requests and upcoming features, so next time please send this kind of questions to support@evasiongames.com. Thanks.

**Comment by Tvisvarson** [comment]
Isn't it kind of an issue? :D 
Seriously, thanks for the Answer, i'm sure this will be a useful feauture. For example when we llike to place footstep sounds.
